---
title: \<SSD Controller/IP Name\> \<SSD_IP_Rev\> \<Block Name\> (\<BLK\>) Microarchitecture Specification
date: build
author: intel_user_name
owner: inteluser_name
---

Authors: Firstname Lastname firstname.lastname@intel.com

[../../../atoms/_copyright.mmd]

# Revision History 
| Revision | Date             | Author          | Major Updates|
| ----     | ----             | -----           | ---------------------------------| 
| 0.1.0  \<Major, Minor, Point\>   | JAN 01, 2022 \<(MMM DD,YYYY)>      | intel_user_name | \<TEXT HERE\>  | 

[../../../atoms/_requirement_terms.mmd]

[!../overview/_overview.mmd]

## Related Documents

* <doc name – Either add a hyperlink to a specific revision (not to the most recent one) or explicitly specify the revision number in front of the document name.>

[!../interface/_interface.mmd]

[!../requirements/_requirements.mmd]

[!../operations/_operations.mmd]

[!../implementation/_implementation.mmd]

[!../troubleshooting/_troubleshooting.mmd]

[!../errata/_errata.mmd]

[!../opens/_opens.mmd]

[!../../../regs/block_regs/block_regs.mmd]
