---
title: Integration Guide (\<IP Name\> \<IP Version\>)
date: build
author: cmark
owner: cmark
---

[../../atoms/_copyright.mmd]

## Revision History 

| Revision | Date             | Updates|
| ----     | ----             | ---------------------------------| 
| 0.1.0  \<Major, Minor, Point\>   | JAN 01, 2022 \<(MMM DD,YYYY)>      | \<TEXT HERE\>  | 0.1.0    | JAN 27, 2022 | Initial Cut of the Integration Guide Template | 


## Related documents

plain text, no revisions, 

<!-- 

Open Topics

* SRAM power management description will need to be updated if we allow the customer to bring their own SRAMS (the SRAM PM needs to follow the specific SRAM, and the specific SRAM follows process). Alternately, we put all SRAMs into an independent macro that can be more easily replaced. 

-- >

[!../definitions/_definitions.mmd]

[!../ip/_ip.mmd]

[!../registers/_reg.mmd]

[!../env/_design_env.mmd]

[!../integration/_integration.mmd]

[!../verification/_verification.mmd]