# Definitions & Notation

<!---
Include definitions section from the HAS
-->

## Definitions

Table: Definitions

| Term | Description | 
| ---- | --------------------------- | 
|      |                             | 

## Notation 

This document assumes the following notation 

Example: 

[!../assets/_template_table_module_signal_list.mmd]

The bit vector `sample_signal_vector` is a packed 3 bits wide vector in a \[2:0\] order.

The array of bit vectors `sample_signal_vector_array` is an unpacked 3 instance array (\[0:2\]) of packed 5 bit wide vectors (\[4:0\]).

The array of interfaces `sample_interface_array` is an unpacked 2 instance array (\[0:1\]) of sample_interface_array interface instances.
