# Registers

## Register Field Types

### Read Only (RO)

Description of read only register behaviour from wiki

### Read Write (RW)

Description of read only register behaviour from wiki

### Read Write Set (RW1S)

Description of read only register behaviour from wiki

### Read Write Set to Clear (RW1C)

Description of read only register behaviour from wiki

## Register Access Transactions

### Valid Access

Pull from wiki, read, write, etc

Sample Valid timing including internal change

### Error

Pull from wiki and register interface MAS, read, write, power, 
Run through the invalid access cases: power down, address not in range, writing to a RO register, writing to a SRAM backed register

## Register Map

The IP registers requires 0x000 to 0xXXXX address space allocation.

Link to top level register map document (washRDL)