| Name                        | Size                    | Type   | Isolation | Modport <br> A | Modport <br> B | Description | 
| ------                      | -----                   | ------ | ---       | -              | -              | ------------------------ | 
| sample_signal_entry         | 1                       | wire   | AON       | I              | O               | description | 
| sample_signal_entry         | 4                       | wire   | AON       | I              | O              | description | 
| sample_signal_entry[array]  | 4                       | wire   | AON       | I              | O             | description | 
| sample_parameter_signal     | 4                       | wire   | AON       | I              | O              | description | 
| sample_struct_entry         | link_to_struct_def      | struct | AON       | O              | I              | description | 
| sample_typedef_entry        | link_to_typedef         | typedef| AON       | -              | I              | description | 