| Name                          | Size               | Type   | Direction | Isolation | Clock     |  Description | 
| ------                        | -----              | ------ | ---       | ---       | ---       | ------------------------ | 
| sample_signal           | 1                  | wire   | input     | AON       | main_clk  | description | 
| sample_signal_vector           | 3                  | wire   | input     | AON       | main_clk  | description | 
| sample_signal_vector_array[3] | 5                  | wire   | input     | AON       | main_clk  | description | 
| sample_parameter        | parameter_name     | wire   | input     | AON       | main_clk  | description | 
| sample_interface        | link_to_struct_definition(s) if applicable <br> | link_to_interface_definition  | \<modport\>    | AON       | main_clk  | Description <br> <br> List any parameters used in instantiation eg AXI size | 
| sample_interface_array[2]        | link_to_struct_definition(s) if applicable <br> | link_to_interface_definition  | \<modport\>    | AON       | main_clk  | Description <br> <br> List any parameters used in instantiation eg AXI size | 