| Signal          | \<modport\> | \<modport\> | Monitor | 
| ------               | - | - | - | 
| sample_signal_entry  | I | O | O | 
| sample_signal_entry  | O | I | O | 
| sample_signal_entry  | I | - | O | 