| Parameter Name  | Type | Description | 
| -----     | ---- | ------------- | 
| sample_struct_parameter | struct | This struct becomes the data | 
| sample_struct_parameter2 | int | This parameter defines the width. <br> Range |
| sample_struct_parameter3 | bool | This parameter turns a feature on and off <br> Range |  
| sample_struct_parameter4 | typedef | This parameter turns a feature on and off <br> Range |  