| Name                          | Size               | Type   | Direction | Isolation | Clock     |  Description | 
| ------                        | -----              | ------ | ---       | ---       | ---       | ------------------------ | 
| sample_signal_entry           | 4                  | wire   | input     | AON       | main_clk  | description | 
| sample_signal_array_entry [3] | 4                  | wire   | input     | AON       | main_clk  | description | 
| sample_parameter_entry        | parameter_name     | wire   | input     | AON       | main_clk  | description | 
| sample_interface_entry        | link_to_struct_definition(s) if applicable <br> | link_to_interface_definition  | \<modport\>    | AON       | main_clk  | Description <br> <br> List any parameters used in instantiation eg AXI size | 