# Tools & Infrastructure 

This section describes the tools and infrastructure used by this IP. 

## Overall Directory Structure

Show locations of in-repo documentation (e.g. release notes), collateral for each flow, RTL, configuration files, etc.

## Global Configuration

Discuss any global configuration/environment variables that the integrator needs to set or may want to override and the mechanism for doing this (editing a .mk, creating a symlink, etc.)

## Included Libraries

List any libraries (e.g. for HIP) included 

## Supported Tools

Simple list of tools that are supported by this IP for a variety of flows. Specific versions can be listed in the release notes.
Example:

* VCS
* UVM
* Nebulon
* Design Compiler
* Spyglass

etc.

## Flow-Specific Information

Provide details on tool execution particular to a flow (like simulation or synthesis) in these subsections. For each flow, give overview of directory structure – README/further documentation, run location, location of key scripts, testbench, any other key information/potential pitfalls etc. If there are files that are expected to modified/customized by integrator, highlight these

### Synthesis

### Lint

### Simulation

### Formal Property Verification

