# Verification Infrastructure

## Simulation 

<!--

Content available in other 3rd party documents are 

Bring up Environment Diagram
Available BFMs
Models
HW Configuration/Initialization
Important Bring Up Sequences (presumably can reference from Programmer's Guide)
Description of a bring up test
-->

## Emulation 

<!--
Reference the Simulation section above as available

Content available in other 3rd party documents are 

Bring up Environment Diagram
Available BFMs
Models
HW Configuration/Initialization
Important Bring Up Sequences (presumably can reference from Programmer's Guide)
Description of a bring up test

There may be some description of what was needed to run the emulation on a sample emulation platform?

-->