# Interface Requirements

## Parameters

[!../../assets/_template_table_parameters.mmd]


## Interface Summary

<!-- Create a copy of the template and store it locally to your mas-->
[!../../assets/_template_table_module_signal_list.mmd]

## \<Sub Interfaces\>
<!-- Create a copy of the template and store it locally to your mas-->
[../../assets/_template_interface.mmd]
